### ISSUE TITLE
split test_version_for 

### ISSUE THREAD

**Issue by OhMyBuggg** [OhMyBuggg/MixInPip#17]
I think you can divide test_version_for into more simple function.
ex: empty simple or something else.

@bilet-13  what do you think?

**Comment by OhMyBuggg** [comment]
and also, I think you can change your file name to "test_versions_for.py".
more simple and more clear.

**Comment by bilet-13** [comment]
> I think you can divide test_version_for into more simple function.
> ex: empty simple or something else.
> 
> @bilet-13 what do you think?

this is good idea, I will do it.

**Comment by bilet-13** [comment]
> and also, I think you can change your file name to "test_versions_for.py".
> more simple and more clear.

I'm not sure what kind of name is proper, how about 'test_finding_versions' ?

**Comment by OhMyBuggg** [comment]
I think test_versions_for is ok?

**Comment by bilet-13** [comment]
> I think test_versions_for is ok?

oh ok ,I see.
